[package]
name = "bast3st-eval"
version = "0.1.0"
edition = "2024"


[dependencies]
bit-set = { version = "0.11.1", default-features = false }
bitflags = { version = "2.13.1", features = ["serde"] }
derive-getters = "0.5.0"
derive_more = { version = "2.1.1", features = ["add", "add_assign", "debug", "deref", "from", "into"] }
either = { version = "1.18.0", features = ["serde"] }
itertools = "0.15.0"
log = "0.4.34"
rand = "0.10.3"
regex = "1.13.1"
reqwest = { version = "0.13.5", features = ["json"] }
scratch-test-interpreter = { git = "https://github.com/marcel-scherzinger/scratch-test-interpreter", version = "0.1.0" }
scratch-test-model = { git = "https://github.com/marcel-scherzinger/scratch-test-model", version = "0.1.0" }
scratch-test-value = { git = "https://github.com/marcel-scherzinger/scratch-test-value", version = "0.1.0", features = ["serde", "thread-share"] }
serde = { version = "1.0.229", features = ["derive", "rc"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version="1.53.1", features=["rt"] }

[dev-dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.11"
tokio = {version="1.53.1",features=["macros", "rt"]}


